#!/bin/bash

HOST="$1"
sharedDir=""
package_files=""
services=""
sync_dirs=""

if [ -z "$HOST" ]; then
    echo "No host defined"
    exit 1
fi

echoerr() { printf "%s\n" "$*" >&2; }

setVars() {
    sharedDir=$1
    package_files="$sharedDir/pkgs"
    services="$sharedDir/services"
    # sync dirs must have trailing /
    sync_dirs="$sharedDir/system/"
    if [ -d "./$HOST" ]; then
        package_files+=" ./$HOST/pkgs"
        services+=" ./$HOST/services"
        # sync dirs must have trailing /
        sync_dirs+=" ./$HOST/system/"
    fi
}


install_packages() {
    for pkgs in $package_files; do
        if [ -f "$pkgs" ]; then
            sudo dnf install --assumeyes $(cat "$pkgs")
        fi
    done
}

enable_services() {
    for svc_file in $services; do
        if [ -f "$svc_file" ]; then
            for svc in $(cat $svc_file); do
                sudo systemctl enable "$svc" --now
            done;
        fi
    done
}

sync_files() {
    for dir in $sync_dirs; do
        if [ -d "$dir" ]; then
            sudo rsync -rv "$dir" /
        fi
    done
}

add_rpmfusion() {
    sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
}

add_vscode() {
    sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
}

desktop() {
    #add_rpmfusion
    #add_vscode
    sudo dnf update --assumeyes --refresh
    # input group for keyoboard-state to work in waybar 
    sudo usermod -a -G input andy
    install_packages
    # remove firefox, flatpak will be installed for better code support
    # fuzzel will be used instead of rofi
    sudo dnf remove firefox rofi -y
    sync_files
    enable_services
}

server() {
    sudo dnf update --assumeyes --refresh
    install_packages
    # Remove network connections as we only want ours there
    sudo rm /etc/NetworkManager/system-connections/*
    sync_files
    # Set appropriate permissions for network
    sudo chmod 0600 /etc/NetworkManager/system-connections/*
    enable_services
    sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
}

addT480Partitions() {
    mkdir -p /mnt/storage
    mkdir -p /mnt/snapshots
    mkdir -p /mnt/git
    mkdir -p /mnt/hass
    if ! grep /mnt/storage /etc/fstab; then
        echo "UUID=3c714e43-7a49-439c-8280-47b069806b97 /mnt/storage btrfs rw,relatime,compress=zstd,ssd,space_cache,subvol=@storage 0 0" | sudo tee -a /etc/fstab
        mount /mnt/storage
    fi
    if ! grep /mnt/snapshots /etc/fstab; then
        echo "UUID=3c714e43-7a49-439c-8280-47b069806b97 /mnt/snapshots btrfs rw,relatime,compress=zstd,ssd,space_cache,subvol=@snapshots 0 0" | sudo tee -a /etc/fstab
        mount /mnt/snapshots
    fi
    if ! grep /mnt/git /etc/fstab; then
        echo "UUID=3c714e43-7a49-439c-8280-47b069806b97 /mnt/git btrfs rw,relatime,compress=zstd,ssd,space_cache,subvol=@git 0 0" | sudo tee -a /etc/fstab
        mount /mnt/git
    fi
    if ! grep /mnt/hass /etc/fstab; then
        echo "UUID=3c714e43-7a49-439c-8280-47b069806b97 /mnt/git btrfs rw,relatime,compress=zstd,ssd,space_cache,subvol=@hass 0 0" | sudo tee -a /etc/fstab
        mount /mnt/hass
    fi
}

createGitUser() {
    if ! id -u git; then
        if ! grep git-shell /etc/shells; then
            echo $(which git-shell) | sudo tee -a /etc/shells
        fi
        sudo useradd git -m -s $(which git-shell)
        sudo mkdir /home/git/.ssh && sudo chmod 700 /home/git/.ssh
        sudo touch /home/git/.ssh/authorized_keys && sudo chmod 600 /home/git/.ssh/authorized_keys
        sudo mkdir /home/git/git-shell-commands
        sudo ln -s /mnt/git /home/git/repos
        sudo chown -R git:git /mnt/git
    fi
    sudo rsync -rv "t480/git/git-shell-commands/" /home/git/git-shell-commands/
    sudo cp t480/git/.gitconfig /home/git/.gitconfig
    sudo chown -R git:git /home/git
}

setupHomeAssistant() {
    # User for home assistant, dialout needed for zigbee stick
    if ! id -u hass; then
        sudo useradd hass -r -m -d /var/lib/hass -G dialout
	# because this is a system account needs extra subuids
	NEW_SUBUID=$(($(tail -1 /etc/subuid |awk -F ":" '{print $2}')+65536))
	NEW_SUBGID=$(($(tail -1 /etc/subgid |awk -F ":" '{print $2}')+65536))
	sudo usermod --add-subuids  ${NEW_SUBUID}-$((${NEW_SUBUID}+65535)) --add-subgids  ${NEW_SUBGID}-$((${NEW_SUBGID}+65535)) hass
	sudo loginctl enable-linger hass
	sudo chown -R hass:hass /mnt/hass
    	sudo setsebool -P container_use_devices 1 #needed for zigbee2mqtt to access device
    fi
    if ! sudo firewall-cmd --zone=FedoraServer --query-port=8123/tcp; then
        sudo firewall-cmd --permanent --zone=FedoraServer --add-port=8123/tcp
        sudo firewall-cmd --reload
    fi
    if ! sudo firewall-cmd --zone=FedoraServer --query-port=8080/tcp; then
        sudo firewall-cmd --permanent --zone=FedoraServer --add-port=8080/tcp
        sudo firewall-cmd --reload
    fi
    if ! sudo ls -ldZ /var/lib/hass | grep user_home_dir_t; then
	sudo semanage fcontext --add --type  user_home_dir_t "/var/lib/hass(/.+)?"
        sudo restorecon -FR /var/lib/hass
    fi
}

setupSamba() {
    if ! sudo firewall-cmd --zone=FedoraServer --query-service=samba; then
        sudo firewall-cmd --permanent --zone=FedoraServer --add-service=samba
        sudo firewall-cmd --reload
    fi
    if ! ls -ldZ /mnt/storage | grep samba_share_t; then
        sudo semanage fcontext --add --type  "samba_share_t" /mnt/storage
        sudo restorecon -R /mnt/storage
    fi
    sudo chown -R ftp:ftp /mnt/storage
    sudo systemctl restart smb
}

addUltra24DataDisk() {
    sudo mkdir -p /mnt/data
    sudo chmod 0777 /mnt/data
    line="UUID=88a3f90a-533e-4503-a951-14049b6ca7b2 /mnt/data       btrfs   subvol=data,compress=zstd:1 0 0"
    if ! grep "$line" /etc/fstab; then
        echo "$line" | sudo tee -a /etc/fstab
    fi
}

addFlathub() {
    sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    sudo flatpak remote-modify --enable flathub
}

case $HOST in
    t480)
        setVars "./shared_server"
        server
        addT480Partitions
        createGitUser
        setupSamba
	setupHomeAssistant
	sudo timedatectl set-ntp yes
        ;;
    razerbook)
        setVars "./shared_desktop"
        desktop
        addFlathub
        ;;
    ultra24)
        setVars "./shared_desktop"
        desktop
	sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
	sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
        addUltra24DataDisk
        addFlathub
        ;;
esac

