#!/bin/bash

HOST="$1"
sharedDir=""
package_files=""
services=""
sync_dirs=""

if [ -z "$HOST" ]; then
    echo "No host defined"
    exit 1
fi

echoerr() { printf "%s\n" "$*" >&2; }

setVars() {
    sharedDir=$1
    package_files="$sharedDir/pkgs"
    services="$sharedDir/services"
    # sync dirs must have trailing /
    sync_dirs="$sharedDir/system/"
    if [ -d "./$HOST" ]; then
        package_files+=" ./$HOST/pkgs"
        services+=" ./$HOST/services"
        # sync dirs must have trailing /
        sync_dirs+=" ./$HOST/system/"
    fi
}


install_packages() {
    for pkgs in $package_files; do
        if [ -f "$pkgs" ]; then
            sudo dnf install --assumeyes $(cat "$pkgs")
        fi
    done
}

enable_services() {
    for svc_file in $services; do
        if [ -f "$svc_file" ]; then
            for svc in $(cat $svc_file); do
                sudo systemctl enable "$svc"
            done;
        fi
    done
}

sync_files() {
    for dir in $sync_dirs; do
        if [ -d "$dir" ]; then
            sudo rsync -rv "$dir" /
        fi
    done
}

add_rpmfusion() {
    sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
}

desktop() {
    add_rpmfusion
    sudo dnf update --assumeyes --refresh
    install_packages
    sync_files
    enable_services
}

server() {
    sudo dnf update --assumeyes --refresh
    install_packages
    sync_files
    enable_services
}

case $HOST in
    t480)
        setVars "./shared_server"
        server
        ;;
    razorbook)
        setVars "./shared_desktop"
        desktop
        ;;
    ultra24)
        setVars "./shared_desktop"
        desktop
        ;;
esac

