#!/bin/bash

dot_dirs="./shared_desktop/home"

if [ ! -z "$HOST" ]; then
    if [ ! -d "./$HOST" ]; then
        echoerr "No directory found for $HOST"
        exit 1
    fi
    dot_dirs+=" ./$HOST/home/"
else
    echo "No host defined, only configuring shared home conf"
fi

create_dirs() {
    for dir in $dot_dirs; do
        if [ -d "$dir" ]; then
            pushd $dir
                to_create=$(find . -mindepth 1 -type d -printf "%P ")
                for d in $to_create; do
                    mkdir -p "$HOME/$d"
                done
            popd
        fi
    done
}

create_links() {
    for dir in $dot_dirs; do
        if [ -d "$dir" ]; then
            pushd $dir
                to_create=$(find . -mindepth 1 -type f -printf "%P ")
                for d in $to_create; do
                    ln -sf "$(pwd)/$d" "$HOME/$d"
                done
            popd
        fi
    done
}

configure_gnome() {
    # Use a dark color scheme
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    
    # Make touchpad usable
    gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false
    gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

    # Set screen turn off delay to 15 mins
    gsettings set org.gnome.desktop.session idle-delay 'uint32 900'

    # Set shortcuts
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Kitty'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'kitty'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>Return'

    # Disable sleep on AC
    gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled false
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

    # Don't use gnome software for updates
    gsettings set org.gnome.software download-updates false
    gsettings set org.gnome.software download-updates-notify false
}

add_global_laravel() {
    composer global require laravel/installer
}

get_fonts() {
    mkdir -p ~/.local/share/fonts

    if [ ! -f ~/.local/share/fonts/SymbolsNerdFont-Regular.ttf ]; then
        wget -o /dev/null -O ~/.local/share/fonts/SymbolsNerdFont-Regular.ttf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFont-Regular.ttf?raw=true
    fi

    if [ ! -f ~/.local/share/fonts/SymbolsNerdFontMono-Regular.ttf ]; then
        wget -o /dev/null -O ~/.local/share/fonts/SymbolsNerdFontMono-Regular.ttf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/NerdFontsSymbolsOnly/SymbolsNerdFontMono-Regular.ttf?raw=true
    fi

    fc-cache -f
}

install_rustup() {
    cd "$HOME" && curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
}

install_flatpaks() {
    flatpak install -y flathub com.github.libresprite.LibreSprite
    flatpak install -y flathub com.valvesoftware.Steam
    flatpak install -y flathub com.valvesoftware.Steam.CompatibilityTool.Proton-GE
    flatpak install -y flathub org.videolan.VLC
    flatpak install -y flathub org.freedesktop.Platform.ffmpeg-full
    flatpak install -y flathub org.mozilla.firefox
    flatpak --user override --socket=wayland --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox
}

create_dirs
create_links
add_global_laravel
#configure_gnome
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
get_fonts
install_rustup
install_flatpaks
